FROM python:2

#MAINTAINER Curtis Hawthorne <fjord@google.com>

# Download and build Magenta.

#ENV MAGENTA_MASTER_REF v0.1.13

# Required for local development
RUN pip install scipy matplotlib intervaltree bokeh magenta requests

RUN mkdir -p /sketch_rnn_floder
WORKDIR /sketch_rnn_floder

RUN git clone https://github.com/mhyz1n4/datalab_sketch_rnn.git

WORKDIR /sketch_rnn_floder/datalab_sketch_rnn/sketch_rnn

RUN touch checkpoints
RUN python sketch_rnn_train_loop.py --log_root=checkpoints --data_dir=data --hparams="data_set=[speedboat.npz],dec_model=lstm,dec_rnn_size=1024,enc_model=lstm,enc_rnn_size=512,conditional=False"
