FROM python:2

RUN mkdir -p /sketch_rnn_floder
WORKDIR /sketch_rnn_floder

RUN pip install tensorflow scipy matplotlib magenta requests

RUN git clone https://github.com/mhyz1n4/datalab_sketch_rnn.git

WORKDIR /sketch_rnn_floder/datalab_sketch_rnn/sketch_rnn

RUN touch checkpoints
RUN python sketch_rnn_train.py --log_root=checkpoints --hparams = "dec_model = lstm, dec_rnn_size = 1024, enc_model = lstm, enc_rnn_size = 512"
